Group.create(name: 'administrator')
Group.create(name: 'supervisor')
Group.create(name: 'clerk')
User.create(login: 'МарковнинВР', password: 'VjFKhOG5', password_confirmation: 'VjFKhOG5')
User.create(login: 'ИвановСК', password: 'tlZPF5si', password_confirmation: 'tlZPF5si')
User.create(login: 'ГудухинАА', password: 'p9fvyL1R', password_confirmation: 'p9fvyL1R')
User.create(login: 'ЛитовКМ', password: 'fBpPXGTa', password_confirmation: 'fBpPXGTa')
User.find_by_login('МарковнинВР').groups << Group.find_by_name('administrator')
User.find_by_login('ИвановСК').groups << Group.find_by_name('supervisor')
User.find_by_login('ГудухинАА').groups << Group.find_by_name('clerk')
User.find_by_login('ЛитовКМ').groups << Group.find_by_name('clerk')
